### PR TITLE
Replaced youtube_dl with yt-dlp

### LINKED ISSUE #17: youtube-dl is Heavily Throttled, Consider supporting yt-dlp
Youtube-dl isn't being supported anymore (last update was in 2021). I'm finding that my downloads are being throttled heavily.

 Could you please consider switching or supporting yt-dlp? It is a fork that is actively supported, has more features, and is faster.

### PR DESCRIPTION
**Pull request by amitalokbera**
Closes #17 

Replaced youtube_dl with yt-dlp to download videos much faster and also made relevant changes in README.md

### CODE REVIEW

**Comment by m1guelpf** [comment]
Can you install it via pip instead? Would like to not add extra friction

**Comment by amitalokbera** [comment]
done

**Comment by BaseInfinity** [comment]
I had to remove the reference to `youtube_dl_log` to get this working on line 7 in `/Users/meow/Library/Python/3.9/lib/python/site-packages/yt_whisper/cli.py` :
```
Traceback (most recent call last):
  File "/Users/meow/Library/Python/3.9/bin/yt_whisper", line 5, in <module>
    from yt_whisper.cli import main
  File "/Users/meow/Library/Python/3.9/lib/python/site-packages/yt_whisper/cli.py", line 7, in <module>
    from .utils import slugify, str2bool, write_srt, write_vtt, youtube_dl_log
ImportError: cannot import name 'youtube_dl_log' from 'yt_whisper.utils' (/Users/meow/Library/Python/3.9/lib/python/site-packages/yt_whisper/utils.py)
```

**Comment by BaseInfinity** [comment]
Thanks for this pull request! The download is sooo much faster

**Comment by m1guelpf** [comment]
Thank you for this! Makes downloads much much faster ❤️

**Pull request merged**
